name: vivify
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.4+3
  google_maps_flutter: ^0.5.25+3
  google_map_polyline: ^0.2.0+1
  geoflutterfire: ^2.1.0
  location: ^3.0.2
  flutter_polyline_points: ^0.1.0
  firebase_ml_vision: ^0.9.3+8
  permission: ^0.1.7
  camera: ^0.5.7+4
  google_sign_in: ^4.4.1
  intent: ^1.1.0
  soundpool: ^1.0.1
  url_launcher: ^5.4.2
  geolocator: ^5.3.1
  rflutter_alert: ^1.0.3
  geocoder: ^0.2.1
  flutter_spinkit: ^4.1.2+1
  provider: ^4.0.5
  flutter_google_places: ^0.2.4
  get_it: ^4.0.1
  shared_preferences: ^0.5.6+3
  flutter_ringtone_player: ^2.0.0
  audioplayers: ^0.15.0
  assets_audio_player: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - Images/
    - assets/

  fonts:
    - family: Quando
      fonts:
        - asset: fonts/Quando.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy.ttf
    - family: Alike
      fonts:
        - asset: fonts/Alike-Regular.ttf
